version: '3'
services:

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - net1
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081    
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongo
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - net1

  front:
    image: front
    build: 
      context: client
      dockerfile: Dockerfile
    container_name: front
    ports: 
      - 3000:80
    networks:
      - net1

  backend:
    image: back
    build: 
      context: server
      dockerfile: Dockerfile
    container_name: backend
    ports: 
      - 5000:5000
    networks:
      - net1

networks:
  net1:
    driver: bridge

volumes:
  mongo-data: 
    driver: local
